/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mawuenyefia.s.restaurant;

import DOC.UserDoc;
import MODEL.User;

/**
 *
 * @author MAWUENYEFIA HUNORKPA
 */
public class CHANGE_SECURITY_QUESTION extends javax.swing.JFrame {

    public String userEmail;

    /**
     * Creates new form CHANGE_SECURITY_QUESTION
     */
    public CHANGE_SECURITY_QUESTION() {
        initComponents();
    }

    public CHANGE_SECURITY_QUESTION(String email) {
        initComponents();
        userEmail = email;
        TEXT_OLD_SQ.setEditable(false);
        btnUpdate.setEnabled(false);

    }

    public void validateField() {
        String password = TEXT_PASSWORD.getText();
        String securityQuestion = TEXT_NEW_SQ.getText();
        String answer = TEXT_NEW_ANSWER.getText();
        if (!password.equals("") && !securityQuestion.equals("") && !answer.equals("")) {
            btnUpdate.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TEXT_PASSWORD = new javax.swing.JPasswordField();
        TEXT_NEW_ANSWER = new javax.swing.JTextField();
        TEXT_NEW_SQ = new javax.swing.JTextField();
        TEXT_OLD_SQ = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/change Security Question.png"))); // NOI18N
        jLabel1.setText("CHANGE SECURITY QUESTION");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close.png"))); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 70, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OLD SECURITY QUESTION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NEW SECURITY QUESTION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NEW ANSWER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        TEXT_PASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_PASSWORD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_PASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_PASSWORDKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 506, -1));

        TEXT_NEW_ANSWER.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_NEW_ANSWER.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_NEW_ANSWER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_NEW_ANSWERKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_NEW_ANSWER, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 506, -1));

        TEXT_NEW_SQ.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_NEW_SQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_NEW_SQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_NEW_SQKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_NEW_SQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 506, -1));

        TEXT_OLD_SQ.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_OLD_SQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TEXT_OLD_SQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 506, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/save.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, 50));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/blue4.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        User user = UserDoc.getSecurityQuestion(userEmail);
        TEXT_OLD_SQ.setText(user.getSecurity_question());

    }//GEN-LAST:event_formComponentShown

    private void TEXT_NEW_SQKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_NEW_SQKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_TEXT_NEW_SQKeyReleased

    private void TEXT_NEW_ANSWERKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_NEW_ANSWERKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_TEXT_NEW_ANSWERKeyReleased

    private void TEXT_PASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_PASSWORDKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_TEXT_PASSWORDKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String password = TEXT_PASSWORD.getText();
        String securityQuestion = TEXT_NEW_SQ.getText();
        String answer = TEXT_NEW_ANSWER.getText();
        UserDoc.changesecurityQuestion(userEmail, password, securityQuestion, answer);
        setVisible(false);
        new CHANGE_SECURITY_QUESTION(userEmail).setVisible(true);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CHANGE_SECURITY_QUESTION(userEmail).setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHANGE_SECURITY_QUESTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHANGE_SECURITY_QUESTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHANGE_SECURITY_QUESTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHANGE_SECURITY_QUESTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHANGE_SECURITY_QUESTION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TEXT_NEW_ANSWER;
    private javax.swing.JTextField TEXT_NEW_SQ;
    private javax.swing.JTextField TEXT_OLD_SQ;
    private javax.swing.JPasswordField TEXT_PASSWORD;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
