/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mawuenyefia.s.restaurant;

import COMMON.OPEN_PDF;
import DOC.BILL_DOC;
import DOC.CATEGORY_DOC;
import DOC.PRODUCT_DOC;
import MODEL.BILL;
import MODEL.CATEGORY;
import MODEL.PRODUCT;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MAWUENYEFIA HUNORKPA
 */
public class PLACE_ORDER extends javax.swing.JFrame {

    public int billId = 1;
    public double grandTotal = 0.0;
    public double productPrice = 0.0;
    public double productTotal = 0.0;
    public String emailPatttern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^(024|025|053|054|055|059|027|057|026|056|020|050)\\d{7}$";
    public String userEmail;
    public String namePattern = "^[a-zA-Z\\s]+$";

    /**
     * Creates new form PLACE_ORDER
     */
    public PLACE_ORDER() {
        initComponents();

    }

    public PLACE_ORDER(String email) {
        initComponents();
        TEXT_PRO_NAME.setEditable(false);
        TEXT_PRO_PRICE.setEditable(false);
        TEXT_PRO_TOTAL.setEditable(false);
        btnAdd_To_Cart.setEnabled(false);
        btnGenerateBill.setEnabled(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        tf.setEditable(false);
        userEmail = email;

    }

    public void ProductNameByCategory(String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<PRODUCT> list = PRODUCT_DOC.getAllRecordsByCategory(category);
        Iterator<PRODUCT> itr = list.iterator();
        while (itr.hasNext()) {
            PRODUCT productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
    }

    public void FilterProductByName(String name, String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<PRODUCT> list = PRODUCT_DOC.FilterProductByName(name, category);
        Iterator<PRODUCT> itr = list.iterator();
        while (itr.hasNext()) {
            PRODUCT productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
        }
    }

    public void ClearProductFields() {
        TEXT_PRO_NAME.setText("");
        TEXT_PRO_PRICE.setText("");
        jSpinner1.setValue(1);
        TEXT_PRO_TOTAL.setText("");
        btnAdd_To_Cart.setEnabled(false);
    }

    public void ValidateField() {
        String customerName = TEXT_CUS_NAME.getText();
        String customermobileNumber = TEXT_CUS_MOBILE.getText();
        String customerEmail = TEXT_CUS_EMAIL.getText();
        if (!customerEmail.equals("") && customerName.matches(namePattern) && customermobileNumber.matches(mobileNumberPattern) && customermobileNumber.length() == 10 && customerEmail.matches(emailPatttern) && grandTotal > 0) {
            btnGenerateBill.setEnabled(true);
        } else {
            btnGenerateBill.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TEXT_CUS_NAME = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TEXT_CUS_MOBILE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TEXT_CUS_EMAIL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TEXT_PRO_NAME = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TEXT_PRO_PRICE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        TEXT_PRO_TOTAL = new javax.swing.JTextField();
        btnAdd_To_Cart = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        LBLGRANT_TOTAL = new javax.swing.JLabel();
        btnGenerateBill = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/place order.png"))); // NOI18N
        jLabel1.setText("PLACE ORDER");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close.png"))); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 20, 80, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BILL ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CUSTOMER DETAILS");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        TEXT_CUS_NAME.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_CUS_NAME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_CUS_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_CUS_NAMEActionPerformed(evt);
            }
        });
        TEXT_CUS_NAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_CUS_NAMEKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_CUS_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MOBILE NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        TEXT_CUS_MOBILE.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_CUS_MOBILE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_CUS_MOBILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_CUS_MOBILEActionPerformed(evt);
            }
        });
        TEXT_CUS_MOBILE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_CUS_MOBILEKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_CUS_MOBILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMAIL ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        TEXT_CUS_EMAIL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_CUS_EMAIL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_CUS_EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_CUS_EMAILActionPerformed(evt);
            }
        });
        TEXT_CUS_EMAIL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_CUS_EMAILKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_CUS_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 280, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CATEGORY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 300, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 300, 370));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, -1));

        TEXT_PRO_NAME.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TEXT_PRO_NAME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_PRO_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_PRO_NAMEActionPerformed(evt);
            }
        });
        getContentPane().add(TEXT_PRO_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 251, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRICE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, -1, -1));

        TEXT_PRO_PRICE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TEXT_PRO_PRICE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TEXT_PRO_PRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 140, 251, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("QUANTITY");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 251, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 200, -1, -1));

        TEXT_PRO_TOTAL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_PRO_TOTAL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_PRO_TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_PRO_TOTALActionPerformed(evt);
            }
        });
        getContentPane().add(TEXT_PRO_TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 230, 251, 40));

        btnAdd_To_Cart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd_To_Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add to cart.png"))); // NOI18N
        btnAdd_To_Cart.setText("ADD TO CART");
        btnAdd_To_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_To_CartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd_To_Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 290, 220, 50));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, -1, 50));

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 640, 450));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("GRAND TOTAL: ");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 840, -1, 50));

        LBLGRANT_TOTAL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LBLGRANT_TOTAL.setForeground(new java.awt.Color(255, 255, 255));
        LBLGRANT_TOTAL.setText("00000");
        getContentPane().add(LBLGRANT_TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 850, 180, 40));

        btnGenerateBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerateBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/generate bill & print.png"))); // NOI18N
        btnGenerateBill.setText("GENERATE BILL & PRINT");
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 840, -1, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/PHOTO12.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HOME(userEmail).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(BILL_DOC.getId());
        jLabel13.setText(BILL_DOC.getId());
        ArrayList<CATEGORY> list = CATEGORY_DOC.getAllRecords();
        Iterator<CATEGORY> itr = list.iterator();
        while (itr.hasNext()) {
            CATEGORY categoryObj = itr.next();
            jComboBox1.addItem(categoryObj.getName());
        }
        String category = (String) jComboBox1.getSelectedItem();
        ProductNameByCategory(category);

    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String productName = model.getValueAt(index, 0).toString();
        PRODUCT product = PRODUCT_DOC.getProductByName(productName);
        TEXT_PRO_NAME.setText(product.getName());
        TEXT_PRO_PRICE.setText(String.valueOf(product.getPrice()));
        jSpinner1.setValue(1);
        TEXT_PRO_TOTAL.setText(String.valueOf(product.getPrice()));
        productPrice = Double.parseDouble(product.getPrice());
        productTotal = Double.parseDouble(product.getPrice());
        btnAdd_To_Cart.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int quantity = (Integer) jSpinner1.getValue();
        if (quantity <= 1) {
            jSpinner1.setValue(1);
            quantity = 1;
        }
        productTotal = productPrice * quantity;
        TEXT_PRO_TOTAL.setText(String.format("%.2f", productTotal));


    }//GEN-LAST:event_jSpinner1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String category = (String) jComboBox1.getSelectedItem();
        ProductNameByCategory(category);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAdd_To_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_To_CartActionPerformed
        // TODO add your handling code here:
        String name = TEXT_PRO_NAME.getText();
        String price = TEXT_PRO_PRICE.getText();
        String quantity = String.valueOf(jSpinner1.getValue());
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name, price, quantity, String.format("%.2f", productTotal)});
        grandTotal = grandTotal + productTotal;
        LBLGRANT_TOTAL.setText(String.format("%.2f", grandTotal));

        ClearProductFields();
        ValidateField();


    }//GEN-LAST:event_btnAdd_To_CartActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ClearProductFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void TEXT_CUS_NAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_CUS_NAMEKeyReleased
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_TEXT_CUS_NAMEKeyReleased

    private void TEXT_CUS_MOBILEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_CUS_MOBILEKeyReleased
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_TEXT_CUS_MOBILEKeyReleased

    private void TEXT_CUS_EMAILKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_CUS_EMAILKeyReleased
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_TEXT_CUS_EMAILKeyReleased

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
        // TODO add your handling code here:
        String customerName = TEXT_CUS_NAME.getText();
        String customerMobile = TEXT_CUS_MOBILE.getText();
        String customerEmail = TEXT_CUS_EMAIL.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todaydate = dFormat.format(date);
        String total = String.format("%.2f", grandTotal);
        String createdBy = userEmail;
        BILL bill = new BILL();
        bill.setId(billId);
        bill.setName(customerName);
        bill.setMobileNumber(customerMobile);
        bill.setEmail(customerEmail);
        bill.setDate(todaydate);
        bill.setTotal(total);
        bill.setCreatedBy(createdBy);
        BILL_DOC.save(bill);

        // CREATING DOCUMENT
        String path = "C:\\\\Users\\\\MAWUENYEFIA HUNORKPA\\\\Desktop\\\\NETBEANS PROJECT\\\\MAWUENYEFIA'S RESTAURANT\\\\RECORDS\\\\";

        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + billId + ".pdf"));

            doc.open();
            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 60);
            Font italicFont = FontFactory.getFont(FontFactory.HELVETICA, 18, Font.ITALIC);

            Paragraph titlePart1 = new Paragraph("TASTY_HUB: ", boldFont);
            Paragraph titlePart2 = new Paragraph(" WHERE FLAVOUR MEETS FUN", italicFont);
            titlePart1.setAlignment(Element.ALIGN_CENTER);
            titlePart2.setAlignment(Element.ALIGN_CENTER);

            doc.add(titlePart1);

            doc.add(titlePart2);
            Paragraph starLine = new Paragraph(" ");
            doc.add(starLine);
            Paragraph paragraph3 = new Paragraph("\tBill ID: " + billId + "\nCustomer Name: " + customerName + "\nTotal Amount Paid: " + grandTotal);
            doc.add(paragraph3);
            doc.add(starLine);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String b = jTable2.getValueAt(i, 0).toString();
                String c = jTable2.getValueAt(i, 1).toString();
                String d = jTable2.getValueAt(i, 2).toString();
                String e = jTable2.getValueAt(i, 3).toString();
                tb1.addCell(b);
                tb1.addCell(c);
                tb1.addCell(d);
                tb1.addCell(e);
            }
            doc.add(tb1);
            doc.add(starLine);
            Paragraph ThanksMess = new Paragraph(" THANK YOU, PLEASE VISIT US AGAIN ", italicFont);
            ThanksMess.setAlignment(Element.ALIGN_CENTER);
            doc.add(ThanksMess);
            Paragraph footer = new Paragraph("TASTY_HUB, GHANA\nCONTACT: 0554303832\nEMAIL: degovernorpf230pf230@gmail.com\nMAWUENYEFIA GROUP OF COMPANIES", italicFont);
            footer.setAlignment(Element.ALIGN_LEFT);
            doc.add(footer);

            OPEN_PDF.OpenById(String.valueOf(billId));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new PLACE_ORDER(createdBy).setVisible(true);
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();
        if (index != -1) { // Ensure a row is selected
            int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product", "Confirm", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                String total = model.getValueAt(index, 3).toString();
                double totalAmount = Double.parseDouble(total); // Parse as double
                grandTotal -= totalAmount; // Update grandTotal
                LBLGRANT_TOTAL.setText(String.valueOf(grandTotal));
                model.removeRow(index); // Remove row from table model
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to remove.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void TEXT_CUS_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_CUS_NAMEActionPerformed
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_TEXT_CUS_NAMEActionPerformed

    private void TEXT_CUS_MOBILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_CUS_MOBILEActionPerformed
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_TEXT_CUS_MOBILEActionPerformed

    private void TEXT_CUS_EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_CUS_EMAILActionPerformed
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_TEXT_CUS_EMAILActionPerformed

    private void TEXT_PRO_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_PRO_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_PRO_NAMEActionPerformed

    private void TEXT_PRO_TOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_PRO_TOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_PRO_TOTALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PLACE_ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PLACE_ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PLACE_ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PLACE_ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PLACE_ORDER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLGRANT_TOTAL;
    private javax.swing.JTextField TEXT_CUS_EMAIL;
    private javax.swing.JTextField TEXT_CUS_MOBILE;
    private javax.swing.JTextField TEXT_CUS_NAME;
    private javax.swing.JTextField TEXT_PRO_NAME;
    private javax.swing.JTextField TEXT_PRO_PRICE;
    private javax.swing.JTextField TEXT_PRO_TOTAL;
    private javax.swing.JButton btnAdd_To_Cart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
