/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mawuenyefia.s.restaurant;

import javax.swing.JOptionPane;
import MODEL.User;
import DOC.UserDoc;

/**
 *
 * @author MAWUENYEFIA HUNORKPA
 */
public class SIGN_UP extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^(024|025|053|054|055|059|027|057|026|056|020|050)\\d{7}$";
    public String namePattern = "^[a-zA-Z\\s]+$";
    

    /**
     * Creates new form SIGN_UP
     */
    public SIGN_UP() {
        initComponents();
        btnSave.setEnabled(false);
    }

    public void clear() {
        TEXT_NAME.setText("");
        TEXT_EMAIL.setText("");
        TEXT_MOBILE_NUMBER.setText("");
        TEXT_ADDRESS.setText("");
        TEXT_SECURITY_QUESTION.setText("");
        TEXT_ANSWER.setText("");
        TEXT_PASSWORD.setText("");
        btnSave.setEnabled(false);
    }

    public void validateFields() {
        String name = TEXT_NAME.getText();
        String email = TEXT_EMAIL.getText();
        String mobileNumber = TEXT_MOBILE_NUMBER.getText();
        String address = TEXT_ADDRESS.getText();
        String password = TEXT_PASSWORD.getText();
        String securityQuestion = TEXT_SECURITY_QUESTION.getText();
        String answer = TEXT_ANSWER.getText();
       
        

        if (name.isEmpty() || !name.matches(namePattern) || !email.matches(emailPattern)
                || !mobileNumber.matches(mobileNumberPattern) || address.isEmpty()
                || password.isEmpty() || securityQuestion.isEmpty() || answer.isEmpty()) {

            btnSave.setEnabled(false);

        } else {
            btnSave.setEnabled(true);

        }
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TEXT_NAME = new javax.swing.JTextField();
        TEXT_EMAIL = new javax.swing.JTextField();
        TEXT_MOBILE_NUMBER = new javax.swing.JTextField();
        TEXT_ADDRESS = new javax.swing.JTextField();
        TEXT_PASSWORD = new javax.swing.JPasswordField();
        TEXT_SECURITY_QUESTION = new javax.swing.JTextField();
        TEXT_ANSWER = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN UP");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 80, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMAIL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MOBILE NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SECURITY QUESTIONS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ANSWER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, -1, -1));

        TEXT_NAME.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_NAME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_NAMEActionPerformed(evt);
            }
        });
        TEXT_NAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_NAMEKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 430, -1));

        TEXT_EMAIL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_EMAIL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_EMAIL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_EMAILKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 430, -1));

        TEXT_MOBILE_NUMBER.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_MOBILE_NUMBER.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_MOBILE_NUMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_MOBILE_NUMBERKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_MOBILE_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 430, -1));

        TEXT_ADDRESS.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_ADDRESS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_ADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_ADDRESSActionPerformed(evt);
            }
        });
        TEXT_ADDRESS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_ADDRESSKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 430, -1));

        TEXT_PASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_PASSWORD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_PASSWORDActionPerformed(evt);
            }
        });
        TEXT_PASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_PASSWORDKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 430, -1));

        TEXT_SECURITY_QUESTION.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_SECURITY_QUESTION.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_SECURITY_QUESTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_SECURITY_QUESTIONActionPerformed(evt);
            }
        });
        TEXT_SECURITY_QUESTION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_SECURITY_QUESTIONKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_SECURITY_QUESTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 430, -1));

        TEXT_ANSWER.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TEXT_ANSWER.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TEXT_ANSWER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_ANSWERKeyReleased(evt);
            }
        });
        getContentPane().add(TEXT_ANSWER, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 430, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("WELCOME TO TASTY_HUB");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 1310, 130));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/save.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, -1, 50));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/exit small.png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, -1, 50));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton2.setText("FORGOT PASSWORD ?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, -1, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, -1, 50));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, -1, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BY: MAWUENYEFIA");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 820, 180, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/pizza.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TEXT_ADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_ADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_ADDRESSActionPerformed

    private void TEXT_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_PASSWORDActionPerformed

    private void TEXT_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_NAMEActionPerformed

    private void TEXT_NAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_NAMEKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_NAMEKeyReleased

    private void TEXT_EMAILKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_EMAILKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_EMAILKeyReleased

    private void TEXT_MOBILE_NUMBERKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_MOBILE_NUMBERKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_MOBILE_NUMBERKeyReleased

    private void TEXT_ADDRESSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_ADDRESSKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_ADDRESSKeyReleased

    private void TEXT_PASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_PASSWORDKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_PASSWORDKeyReleased

    private void TEXT_SECURITY_QUESTIONKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_SECURITY_QUESTIONKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_SECURITY_QUESTIONKeyReleased

    private void TEXT_ANSWERKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_ANSWERKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_TEXT_ANSWERKeyReleased

    private void TEXT_SECURITY_QUESTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_SECURITY_QUESTIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_SECURITY_QUESTIONActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setName(TEXT_NAME.getText());
        user.setEmail(TEXT_EMAIL.getText());
        user.setMobile_number(TEXT_MOBILE_NUMBER.getText());
        user.setAddress(TEXT_ADDRESS.getText());
        user.setPassword(TEXT_PASSWORD.getText());
        user.setSecurity_question(TEXT_SECURITY_QUESTION.getText());
        user.setAnswer(TEXT_ANSWER.getText());
        UserDoc.save(user);
        clear();
    }//GEN-LAST:event_btnSaveActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new FORGOT_PASSWORD().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LOGIN().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close this Application ?", "selet", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGN_UP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TEXT_ADDRESS;
    private javax.swing.JTextField TEXT_ANSWER;
    private javax.swing.JTextField TEXT_EMAIL;
    private javax.swing.JTextField TEXT_MOBILE_NUMBER;
    private javax.swing.JTextField TEXT_NAME;
    private javax.swing.JPasswordField TEXT_PASSWORD;
    private javax.swing.JTextField TEXT_SECURITY_QUESTION;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
